<!--///////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////--DISH--//////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<?php if (empty($resultSearch)): ?>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Recherche</h1>
            <p class="lead">Aucun résultat pour la recherche "<?= $search ?>"</p>
        </div>
    </div>
<?php endif;?>
<div class="uk-section uk-section-default uk-padding-remove-top">
    <div class="uk-container">
        <div data-uk-grid>
            <div class="uk-width-1-2@m">
                <form class="uk-search uk-search-default uk-width-1-1 uk-margin-small-bottom" method="GET" action="<?= Router::getInstance()->generateUrl('resto_dish_search')?>?>">
                    <span data-uk-search-icon></span>
                    <input class="uk-search-input uk-text-small uk-border-rounded uk-form-large" name="q" type="search" placeholder="Cherche ta recette...">
                    <button type="submit" hidden></button>
                </form>
            </div>
        </div>
        <div class="uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-margin-medium-top" data-uk-grid>
            <?php if (isset($resultSearch)): ?>
                <?php foreach ($resultSearch as $detail): ?>
                    <div>
                        <div class="uk-card">
                            <div class="uk-card-media-top uk-inline uk-light">
                                <img class="uk-border-rounded-medium" src="https://via.placeholder.com/300x160" alt="Course Title">
                                <div class="uk-position-cover uk-card-overlay uk-border-rounded-medium"></div>
                                <div class="uk-position-xsmall uk-position-top-right">
                                    <img src="<?= $detail['flag']?>" alt="<?= $detail['country']?>" style="width:25px; border-radius:50px" class="uk-like uk-position-z-index uk-position-relative">
                                </div>
                            </div>
                            <div>
                                <h3 class="uk-card-title uk-text-500 uk-margin-small-bottom uk-margin-top"><?= $detail['name']?></h3>
                                <div class="uk-text-xsmall uk-text-muted" data-uk-grid>
                                    <?php if (isset($detail['note'])):?>
                                        <div class="uk-width-auto uk-flex uk-flex-middle">
                                            <span class="uk-rating-<?php if ($detail['note']<1):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                            <span class="uk-rating-<?php if ($detail['note']<2):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                            <span class="uk-rating-<?php if ($detail['note']<3):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                            <span class="uk-rating-<?php if ($detail['note']<4):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                            <span class="uk-rating-<?php if ($detail['note']<5):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                            <span> (<?= $detail['com']?>)</span>
                                        </div>
                                    <?php endif?>
                                    <div class="uk-width-expand uk-text-right">Par <?= $detail['forname']?> <?= $detail['lastname']?></div>
                                </div>
                            </div>
                            <a  href="<?= Router::getInstance()->generateUrl('resto_dish_showone')?>?id=<?= $detail["dishId"] ?>" class="uk-position-cover"></a>
                        </div>
                    </div>
                <?php endforeach;?>
            <?php endif;?>
        </div>

    </div>
</div>

