<!--///////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////--USER--//////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

<?php foreach(Flashbag::getInstance()->consumeAllMessage() as $message):?>
    <div class="alert" style="text-align: center;background-color:<?php if (stristr($message,"bien") == TRUE):?>forestgreen<?php else:?>red<?php endif;?>">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <?= $message ?>
    </div>
<?php endforeach; ?>
<div class="uk-grid-collapse" data-uk-grid>
    <div class="uk-width-1-2@m uk-padding-large uk-flex uk-flex-middle uk-flex-center" data-uk-height-viewport>
        <div class="uk-width-3-4@s">
            <div class="uk-text-center uk-margin-medium-bottom">
                <h1 class="uk-h2 uk-letter-spacing-small">Inscription</h1>
            </div>
            <div data-uk-grid class="uk-child-width-auto uk-grid-small uk-flex uk-flex-center uk-margin">
                <div>
                    <a href="#" data-uk-icon="icon: facebook" class="uk-icon-button uk-icon-button-large facebook"></a>
                </div>
                <div>
                    <a href="#" data-uk-icon="icon: google-plus" class="uk-icon-button uk-icon-button-large google-plus"></a>
                </div>
                <div>
                    <a href="#" data-uk-icon="icon: linkedin" class="uk-icon-button uk-icon-button-large linkedin"></a>
                </div>
            </div>
            <form class="uk-text-center" method="POST" action="<?= $router->generateUrl("resto_user_create") ?>" id="create-profil" enctype="multipart/form-data" data-validate>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="forname">Prenom</label>
                    <input name="forname"  id="forname" data-minlength="2" class="uk-input uk-form-large uk-border-pill uk-text-center" type="text" placeholder="Tom Atkins">
                </div>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="lastname">Nom</label>
                    <input name="lastname" id="lastname" data-minlength="2" class="uk-input uk-form-large uk-border-pill uk-text-center" type="text" placeholder="Tom Atkins">
                </div>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="create-mail">Email</label>
                    <input name="email" id="create-mail" class="uk-input uk-form-large uk-border-pill uk-text-center" type="email" placeholder="tom@company.com">
                </div>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="create-password">Mot de Passe</label>
                    <input name="password" id="create-password" data-equalcopy="password" class="uk-input uk-form-large uk-border-pill uk-text-center" type="password" placeholder="*******">
                </div>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="create-confirm">Confirmer le Mot de Passe</label>
                    <input name="confirm-password" id="create-confirm" data-equalcopy="password" class="uk-input uk-form-large uk-border-pill uk-text-center" type="password" placeholder="*******">
                </div>
                <div class="uk-width-1-1 uk-text-center">
                    <button class="uk-button uk-button-primary uk-button-large" type="submit" name="save">Enregistrer</button>
                </div>
                <div class="uk-width-1-1 uk-margin uk-text-center">
                    <p class="uk-text-small uk-margin-remove">By signing up you agree to our <a class="uk-link-border" href="#">terms</a> of service.</p>
                </div>
            </form>
        </div>
    </div>
    <div class="uk-width-1-2@m uk-padding-large uk-flex uk-flex-middle uk-flex-center uk-light" data-uk-height-viewport>
        <div class="uk-background-cover uk-background-norepeat uk-background-blend-overlay uk-background-overlay
      uk-border-rounded-large uk-width-1-1 uk-height-xlarge uk-flex uk-flex-middle uk-flex-center"
             style="background-image: url(<?= Router::getInstance()->getWwwPath()?>/img/signIn.jpeg);">
            <div class="uk-padding-large">
                <div class="uk-text-center">
                    <h2 class="uk-letter-spacing-small">Vous etes Membre !</h2>
                </div>
                <div class="uk-margin-top uk-margin-medium-bottom uk-text-center">
                    <p>Déjà inscrit, entrez vos coordonnées et commencez à cuisiner votre premier repas aujourd'hui</p>
                </div>
                <div class="uk-width-1-1 uk-text-center">
                    <a href="<?= Router::getInstance()->generateUrl('resto_user_login')?>" class="uk-button uk-button-primary uk-button-large">Connexion</a>
                </div>
            </div>
        </div>
    </div>
</div>
