<!--///////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////--USER--//////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

<?php foreach(Flashbag::getInstance()->consumeAllMessage() as $message):?>
    <div class="alert" style="text-align: center;background-color:<?php if (stristr($message,"bien") == TRUE):?>forestgreen<?php else:?>red<?php endif;?>">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <?= $message ?>
    </div>
<?php endforeach; ?>

<div class="uk-grid-collapse" data-uk-grid>
    <div class="uk-width-1-2@m uk-padding-large uk-flex uk-flex-middle uk-flex-center" data-uk-height-viewport>
        <div class="uk-width-3-4@s">
            <div class="uk-text-center uk-margin-bottom">
                <a class="uk-logo uk-text-primary uk-text-bold" href="<?= Router::getInstance()->generateUrl('resto_home_main')?>">Cuisine Cool</a>
            </div>
            <div class="uk-text-center uk-margin-medium-bottom">
                <h1 class="uk-h2 uk-letter-spacing-small">Connexion à CuisineCool</h1>
            </div>
            <div data-uk-grid class="uk-child-width-auto uk-grid-small uk-flex uk-flex-center uk-margin">
                <div>
                    <a href="#" data-uk-icon="icon: facebook" class="uk-icon-button uk-icon-button-large facebook"></a>
                </div>
                <div>
                    <a href="#" data-uk-icon="icon: google-plus" class="uk-icon-button uk-icon-button-large google-plus"></a>
                </div>
                <div>
                    <a href="#" data-uk-icon="icon: linkedin" class="uk-icon-button uk-icon-button-large linkedin"></a>
                </div>
            </div>

            <form class="uk-text-center" method="POST" action="<?= $router->generateUrl("resto_user_login") ?>" autocomplete="OFF" id="create" data-validate>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="email">Email</label>
                    <input id="email" class="uk-input uk-form-large uk-border-pill uk-text-center" type="email" name="email" placeholder="********@******.**" data-required>
                </div>
                <div class="uk-width-1-1 uk-margin">
                    <label class="uk-form-label" for="mdp">Mot de Passe</label>
                    <input id="mdp" class="uk-input uk-form-large uk-border-pill uk-text-center" type="password"name="password" placeholder="********" data-required>
                </div>
                <div class="uk-width-1-1 uk-text-center">
                    <button class="uk-button uk-button-primary uk-button-large" type="submit" name="login">Connexion</button>
                </div>
            </form>
        </div>
    </div>
    <div class="uk-width-1-2@m uk-padding-large uk-flex uk-flex-middle uk-flex-center uk-light" data-uk-height-viewport>
        <div class="uk-background-cover uk-background-norepeat uk-background-blend-overlay uk-background-overlay
      uk-border-rounded-large uk-width-1-1 uk-height-xlarge uk-flex uk-flex-middle uk-flex-center"
             style="background-image: url(<?= Router::getInstance()->getWwwPath()?>/img/signUp.jpeg);">
            <div class="uk-padding-large">
                <div class="uk-text-center">
                    <h2 class="uk-letter-spacing-small">Bonjour, Rejoignez-nous</h2>
                </div>
                <div class="uk-margin-top uk-margin-medium-bottom uk-text-center">
                    <p>Entrez vos informations personnelles et rejoignez la communauté de CuisineCool</p>
                </div>
                <div class="uk-width-1-1 uk-text-center">
                    <a href="<?= Router::getInstance()->generateUrl('resto_user_create')?>" class="uk-button uk-button-primary uk-button-large">S'inscrire</a>
                </div>
            </div>

    </div>

