<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">
            <img class="lead" src="<?= $state['flag'] ?>" alt="Tous nos Plats de la Categorie <?= $state['country'] ?>">
            <?= $state['country'] ?>
        </h1>
        <p class="lead"><?= $state['description'] ?></p>
    </div>
</div>


<div class="uk-section uk-section-default uk-padding-remove-top">
    <div class="uk-container">
        <?php foreach(Flashbag::getInstance()->consumeAllMessage() as $message):?>
            <div class="alert" style="text-align: center;background-color:<?php if (stristr($message,"traitement") == TRUE):?>forestgreen<?php else:?>red<?php endif;?>">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <?= $message ?>
            </div>
        <?php endforeach; ?>
        <div class="container">
            <div class="row">
                <div class="col-12 mb-4">
                    <form class="alert alert-dismissible alert-success" method="POST" action="<?= $router->generateUrl("resto_state_show")?>?id=<?= $state['id']?>" enctype="multipart/form-data" data-validate tabindex="-1">
                        <div class="form-group row col-12">
                            <div class="col-6">
                                <label for="name" style="margin-left: 1%">Pseudo :</label><br>
                                <input class="form-control" name="name" id="name">
                            </div>
                            <div class="col-6 "">
                                <label style="margin-left: 1%"></label><br>
                                <input type="hidden" name="note" value="" id="note"/>
                                <i id="clear_stars" class="fa fa-times-circle"  style="font-size: 20px;margin-top: 10px"></i>
                                <span id="star_1" class="star uk-rating-star" data-uk-icon="icon: star; ratio: 1"></span>
                                <span id="star_2" class="star uk-rating-star" data-uk-icon="icon: star; ratio: 1"></span>
                                <span id="star_3" class="star uk-rating-star" data-uk-icon="icon: star; ratio: 1"></span>
                                <span id="star_4" class="star uk-rating-star" data-uk-icon="icon: star; ratio: 1"></span>
                                <span id="star_5" class="star uk-rating-star" data-uk-icon="icon: star; ratio: 1"></span>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group row col-12">
                            <div class="form-group col-8">
                                <label for="description" style="margin-left: 1%">Description :</label><br>
                                <input class="form-control" name="description" id="description">
                                <input type="text" name="stateId" value="<?= $state['id']?>" hidden="hidden">
                            </div>
                            <div class="form-group col-3">
                                <label  style="margin-left: 1%"></label><br>
                                <button class="uk-button uk-button-primary" type="submit" style="margin: 3%">Publier</button>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
        <?php foreach($allCommentByPage as $detail):?>
            <?php if ($detail['statu'] == "approuver"):?>
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="alert alert-dismissible alert-primary">
                            <div class="row">
                                <div class="col-2">
                                    <h4 class="alert-heading"><?= $detail['nameCom']?></h4>
                                </div>
                                <div class="col-3">
                                    <span class="uk-rating-<?php if ($detail['note']<1):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                    <span class="uk-rating-<?php if ($detail['note']<2):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                    <span class="uk-rating-<?php if ($detail['note']<3):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                    <span class="uk-rating-<?php if ($detail['note']<4):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                    <span class="uk-rating-<?php if ($detail['note']<5):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                </div>

                            </div>

                            <?= $detail['date']?>
                            <hr>
                            <p class="mb-0">
                                <?= $detail['descripCom']?>
                            </p>
                        </div>
                    </div>
                </div>


            <div class="container-fluid">
                <hr>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <div class="uk-margin-large-top uk-text-small">
        <ul class="uk-pagination uk-flex-center uk-text-500 uk-margin-remove" data-uk-margin>
            <li>
                <a href="<?= Router::getInstance()->generateUrl('resto_state_show')?>?id=<?=$state['id']?>&amp;page=<?= $pageCourant - 1 ?>#test">
                    <span data-uk-pagination-previous></span>
                </a>
            </li>
            <?php for ($i=1;$i<=$totalPage;$i++): ?>
                <?php if ($i == $pageCourant): ?>
                    <li><?=$i?></li>
                <?php else: ?>
                    <li class="uk-active">
                        <span><a href="<?= Router::getInstance()->generateUrl('resto_state_show')?>?id=<?=$state['id']?>&amp;page=<?=$i?>#test"><?=$i?></a></span>
                    </li>
                <?php endif ?>
            <?php endfor;?>
            <li>
                <a href="<?= Router::getInstance()->generateUrl('resto_state_show')?>?id=<?=$state['id']?>&amp;page=<?= $pageCourant + 1 ?>#test">
                    <span data-uk-pagination-next></span>
                </a>
            </li>
        </ul>
    </div>
        <div class="container-fluid mb-5 mt-5">
            <h3>Tous les Plats de la catégorie : <?= $state['country'] ?></h3>
        </div>

        <div class="uk-child-width-1-2 uk-child-width-1-3@s" data-uk-grid>
            <?php foreach($allDishByState as $detail): ?>
                <div>
                    <div class="uk-card">
                        <div class="uk-card-media-top uk-inline uk-light">
                            <img class="uk-border-rounded-medium" src="<?= $router->getWwwPath()?>/uploads/dish/<?= $detail['img']?>" alt="<?= $detail['name']?>" >
                            <div class="uk-position-cover uk-card-overlay uk-border-rounded-medium"></div>
                            <div class="uk-position-xsmall uk-position-top-right">
                                <img src="<?= $detail['flag']?>" alt="<?= $detail['country']?>" style="width:25px; border-radius:50px" class="uk-like uk-position-z-index uk-position-relative">
                            </div>
                        </div>
                        <div>
                            <h3 class="uk-card-title uk-text-500 uk-margin-small-bottom uk-margin-top"><?= $detail['name']?></h3>
                            <div class="uk-text-xsmall uk-text-muted" data-uk-grid>
                                <?php if (isset($detail['note'])):?>
                                    <div class="uk-width-auto uk-flex uk-flex-middle">
                                        <span class="uk-rating-<?php if ($detail['note']<1):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                        <span class="uk-rating-<?php if ($detail['note']<2):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                        <span class="uk-rating-<?php if ($detail['note']<3):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                        <span class="uk-rating-<?php if ($detail['note']<4):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                        <span class="uk-rating-<?php if ($detail['note']<5):?>star<?php else:?>filled<?php endif;?>" data-uk-icon="icon: star; ratio: 1"></span>
                                        <span> (<?= $detail['com']?>)</span>
                                    </div>
                                <?php endif?>
                                <div class="uk-width-expand uk-text-right">Par <?= $detail['forname']?> <?= $detail['lastname']?></div>
                            </div>
                        </div>
                        <a href="<?= Router::getInstance()->generateUrl('resto_dish_showone')?>?id=<?= $detail["dishId"] ?>" class="uk-position-cover"></a>
                    </div>
                </div>
            <?php endforeach; ?>

    </div>
</div>